version: '3.3'
services:
    webdjicontrollws:
        #container_name: micro_web
        build: webdjicontrollws/
        ports:
            - "80:80"
        image: webdjicontrollws

    sockerserver:
        image: sockerserver
        build: sockerserver/
        environment:
            - DB_HOST=db
        # env_file:
        #     - ".env"
        ports:
            - "3000:3000"
            - "8080:8080"
        depends_on:
            - db
            # db:
            #     condition: service_healthy

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: dboids
            MYSQL_USER: dboids
            MYSQL_PASSWORD: dboids
        ports:
        - "3306:3306"
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./db/data:/var/lib/mysql
        # healthcheck:
        #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        #     timeout: 3s
        #     retries: 10
        #volumes:
            #