version: '3.3'
services:
    webdjicontrollws:
        #container_name: micro_web
        build: webdjicontrollws/
        ports:
            - "80:80"
        image: webdjicontrollws
        env_file:
            - "webdjicontrollws/.env"

    sockerserver:
        image: sockerserver
        build: sockerserver/
        environment:
            - DATABASE_URL=db
            - DATABASE_USER=dboids
            - DATABASE_PASSWORD=dboids
            - DATABASE_NAME=dboids_db
            - DATABASE_PORT=3306
        # env_file:
        #     - ".env"
        ports:
            - "3000:3000"
            - "8080:8080"
        depends_on:
            #- db
            db:
                condition: service_healthy

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: dboids
            MYSQL_USER: dboids
            MYSQL_PASSWORD: dboids
            MYSQL_DATABASE: dboids_db
        ports:
          - "3306:3306"
        #Para persistir info é só decomentar a linha abaixo
        #volumes:
        #  - ./db/data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
